### ISSUE TITLE
Retrieving an array of rows from a table

### ISSUE THREAD

**Issue by jeanhdev** [appledeveloperacademypucrs/AirtableKit#25]
Hi,

I want to extract from AirTable each row of my table and make it onto an array.

Each row is a bubble with different attributes (columns of my table) a name, a URL to a logo and a size. 

I would like to be able to extract from AirTable all of the rows (bubbles), iterate on them like I would do with a for loop.

To be more precise : I would like to obtain an array of sub arrays that are my rows from AirTable.

I don't know how to implement that... any idea ? Thanks 

PS: I need to do so in a GameScene because each row will generate a SpriteKitNode

**Comment by rafaelruwer** [comment]
Hi @jeadev!

Sorry for the long delay. If this is still relevant to you, I created a small example of how you can parse the records from a table in your Airtable base.

The package uses [Combine](https://developer.apple.com/documentation/combine/) as its interface for returning the status of operations performed (create, delete) or the data requested (list, get). Given that Combine is a new framework, let's say you're using closures instead of Combine on your application.

I'm considering you have a class to encapsulate communication with Airtable. You can do something like the following:

```swift
import Combine
import AirtableKit

class Service {
    
    private let airtable = Airtable(baseID: "<your base id>", apiKey: "<your API key>")
    private var subscriptions: [AnyCancellable] = []
    
    func listStudents(completion: @escaping (Result<[[String]], Error>) -> Void) {
        airtable.list(tableName: "<your table name>")
            .sink { completionEvent in
                switch completionEvent {
                case .finished:
                    // you can ignore this
                    print("successfully finished")
                case .failure(let error):
                    print("got error \(error)")
                    completion(.failure(error))
                }
            } receiveValue: { records in
                print("records \(records)")
                
                let content = records.map { record -> [String] in
                    // map your record/row here
                    
                    var result = [String]()
                    
                    if let name = record.fields["Name"] as? String {
                        result.append(name)
                    }
                    
                    if let logo = record.attachments["Picture"]?.first {
                        let logoUrl = logo.url.absoluteString
                        let logoSize = logo.metadata["size"] as? Int ?? 0
                        
                        result.append(logoUrl)
                        result.append("\(logoSize)")
                    }
                    
                    return result
                }
                
                completion(.success(content))
                
            }
            .store(in: &subscriptions)
    }
}
```

Now to use it on your app:

```swift
let service = Service()

func getDataFromAirtable() {
    service.listStudents { result in
        switch result {
        case .success(let rows):
            // do something with rows
            print("result: success \(rows)")
        case .failure(let error):
            // handle this as you wish
            print("result: error \(error)")
        }
    }
}
```

I haven't written SpriteKit code for some time now, but I think you can use this as a starting point to implement what you need.

I'll close this for now, but feel free to comment and I'll see how I can help.
